version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install awscli

  pre_build:
    commands:
      - echo "Preparing for deployment..."

  build:
    commands:
      - echo "Building application..."
      - cd backend && docker build -t special-days-backend .
      - cd ../frontend && docker build -t special-days-frontend .

  post_build:
    commands:
      - echo "Deploying to EC2..."
      - scp -o StrictHostKeyChecking=no -r ../special-days-calendar ec2-user@$EC2_INSTANCE_IP:/home/ec2-user/
      - ssh -o StrictHostKeyChecking=no ec2-user@$EC2_INSTANCE_IP "cd /home/ec2-user/special-days-calendar && docker-compose up -d"